### ISSUE TITLE
Request: Support for ESP32

### ISSUE THREAD

**Issue by hicotton02** [marcoschwartz/aREST#137]
I have a sparkfun ESP32 Thing and am trying to get aREST to work. I believe it is exactly the same as the ESP8266 as far as your implementation goes. I sent an email to contact@arest.io, then thought I probably should have mentioned it here. I am currently using the Arduino IDE for my development.

**Comment by marcoschwartz** [comment]
Hi! Support for the ESP32 is definitely on the way, it's actually already coded in the experimental branch of aREST and uses https://github.com/espressif/arduino-esp32. Currently I still have some issues with compiling, for example because the missing analogWrite() function. Once it compiles fine, I will push the changes here :)

**Comment by hicotton02** [comment]
awesome! looking forward to it.

**Comment by vaishaks** [comment]
I'm looking forward to this as well. I'll be glad to help in any way I can :)

**Comment by pablonunez** [comment]
+1

**Comment by marcoschwartz** [comment]
I just added support for the ESP32 chip via https://github.com/espressif/arduino-esp32 ! There might still be some bugs, please open a dedicated issue if you find some :)

**Comment by vaishaks** [comment]
@marcoschwartz Thank you! I will be trying this out
