### ISSUE TITLE
[Due] avr/wdt.h: No such file or directory

### ISSUE THREAD

**Issue by ATsimon** [marcoschwartz/aREST#33]
I am trying to build the WiFi_CC3000 example for the Arduino Due but keep running into the following error:

WiFi_CC3000.ino:13:21: fatal error: avr/wdt.h: No such file or directory

I am using the Arduino 1.6.0 IDE on OS X 10.10.2 but have also tried with Arduino 1.5.7 which the guide suggests but also receive the same error.

Thanks.

**Comment by marcoschwartz** [comment]
For the Due you need to comment out all the lines concerning the Watchdog. I will put another example soon specifically for the Due, but for now you can just remove these lines and it should be compiling just fine :)

**Comment by ATsimon** [comment]
Ok that's great, thanks for the response!

**Comment by marcoschwartz** [comment]
Ok, example is online :) Let me know if it works.

**Comment by ATsimon** [comment]
Thanks Marco,

I'll check it out when I get some spare time!

**Comment by buxtehude04** [comment]
Hi friend,

Could you be so kind enough to help and showing me how i could use or call the wdt function for a code which should be executed in a Arduino Due board?

I  need to use this resource because, I have not been able so far for implement a obligatory reset for synchronize a gprs shield, which only begin to answer at commands until i push down the reset button.

I tried implement differents circuits that generate and could hold the reset even if the board started to reset. Looking the reset signal through a osciloscope i could see the the signal generated by the annexed circuit in the reset pin of the board is identical to the reset signal generated pressing the reset button. I cant understand why the reset of the circuit can't do the same work that the manual reset.

My last resource is use the wdt function.

Thank you for your help.

Best Regards...

Brian

**Comment by marcoschwartz** [comment]
Hi Brian, using the watchdog on the Due is a complicated issue, and I haven't played with it myself (yet). What I recommend is checking out the Arduino forum, for example: http://forum.arduino.cc/index.php?topic=233175.0#
