### ISSUE TITLE
[Question] Overwriting memory?

### ISSUE THREAD

**Issue by NicoHood** [marcoschwartz/aREST#36]
I just looked through the code and have a simple question:

Am I wrong or are you missing to use reallocate the memory here? Arent you overwriting the pointer borders?
https://github.com/marcoschwartz/aREST/blob/master/aREST.h#L753

Same for other arrays

**Comment by marcoschwartz** [comment]
It can be, I am not the best expert in C/C++ :) What should I be doing to make a better usage of the memory?

**Comment by NicoHood** [comment]
```cpp
if( int_variables[variables_index<NUMBER_VARIABLES){
code
}
else
do nothing?
```

You are using templates and not a c++ expert? Someone should really have a look at your code or it might end with a lot of crashes or unexpected behavior.

**Comment by marcoschwartz** [comment]
Agreed for that, there should be a check if we already filled the array or not. I'll make sure to add it.

Also what did you mean by "reallocate the memory"? Is that the same issue?

As I said, I have a good knowledge of C++, otherwise I wouldn't have created this library, but I don't claim to know all. I also have a series of test based on Node.js that I run on a live Arduino after each modification of the library to make sure all the functionalities are working.

**Comment by NicoHood** [comment]
You can use static array size (like right now) and check for overflow (code above) or you can dynamically reallowcate the array and make it variable like a string or a c++ vector. Static should be smaller implementation and fine. just check for overflows to not exceed the array limit and write to memory the function shouldnt write to.
