### ISSUE TITLE
Add support for other HTTP methods

### ISSUE THREAD

**Issue by ziolek** [marcoschwartz/aREST#47]
Using methods other than HTTP is crucial in RESTful API.

Please consider adding at least PUT method to your implementation. It would be useful for changing states of the outputs.

Thanks.

**Comment by marcoschwartz** [comment]
Hello,

This is definitely the goal. However because of memory space reasons this feature could be limited to boards with sufficient memory space like the Mega, Due, and other boards like the ESP8266 WiFi chip. I dont think this will be possible with Uno boards.

I'll mark this as feature request and update it as progres is made :)

**Comment by ziolek** [comment]
Do you mean insufficient program memory?

**Comment by marcoschwartz** [comment]
Yes indeed. Already with aREST + the CC3000 library the program memory of the Uno is nearly full.

**Comment by geoak** [comment]
I understand the problem with those boards that have small memory, and these are the boards used for most project prototypes, but at the end of he day everyone uses a larger board for the final impementation. 

Maybe there is a seperate version with not all the library capabilities for the borads like Arduino Uno.

Memory is already getting larger on all other boards and we should work on providing more functionality for the aRest library.

**Comment by marcoschwartz** [comment]
Closing this for now as we put it in our internal to-do list to implement that :) Also we removed support for the CC3000 so memory shouldn't be an issue anymore.
